what problem  we solving using linear regression

In [1]:
# this algo is to solve the regression problem and the output freature is countinious

In [2]:
# resideal error mean distance bet actual point and predicted point

In [3]:
# linear algo aim is to find the best fit line with minimal error

In [4]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


# Linear Regression Practical Implementation

In [5]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [6]:
data_frame = pd.read_csv("Salary_Data.csv")

In [7]:
df = data_frame.copy()

In [8]:
df

YearsExperience  Salary
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 608.0 bytes


In [10]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [11]:
X = df.drop("Salary", axis = 1)
y = df["Salary"]

In [12]:
X.head()

YearsExperience
0              1.1
1              1.3
2              1.5
3              2.0
4              2.2

In [13]:
y.head()

0    39343
1    46205
2    37731
3    43525
4    39891
Name: Salary, dtype: int64

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 0, test_size = 0.30)

In [16]:
print(X_train.shape)

(21, 1)


In [17]:
X_test.shape

(9, 1)

In [18]:
# stadardizing the dataset
from sklearn.linear_model import LinearRegression

In [19]:
model = LinearRegression()

In [20]:
model.fit(X_train,y_train)

LinearRegression()

In [21]:
model.predict([[101302]])

array([9.48239966e+08])

In [22]:
model.predict([[1200000]])

array([1.12323403e+10])

In [23]:
model.predict([[150000]])

array([1.40406597e+09])

In [24]:
model.predict([[12000]])

array([1.12349913e+08])

In [25]:
model.predict([[50000]])

array([4.68039842e+08])